- name: start and enable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: yes

- name: start and enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: yes

- name: start and enable nftables
  ansible.builtin.systemd:
    name: nftables
    enabled: yes

- name: start and enable chrony
  ansible.builtin.systemd:
    name: chrony
    enabled: yes
