- name: apt-get install packages
  apt:
    pkg:
      - chrony
      - screen
      - tree
      - nftables
      - iftop
      - zsh
      - tcpdump
      - netsniff-ng
      - net-tools
      - mtr
      - sudo
      - emacs
      - netcat
      - socat
      - htop
      - dnsutils
      - curl
      - parallel
      - jq
      - python3-pip
      - git
      - nmap
      - docker-compose
