- name: start and enable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: yes

- name: start and enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: yes

- name: start and enable nftables
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: yes

- name: start and enable chrony
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: yes